import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");
const IMAGE_HEIGHT = 320;

export { IMAGE_HEIGHT };

export function createSpaceDetailStyles(colors) {
  return StyleSheet.create({
    container: { flex: 1 },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
      gap: 14,
    },
    loadingPulse: {
      width: 72,
      height: 72,
      borderRadius: 36,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingText: { fontSize: 14, fontWeight: "600" },
    stickyHeader: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      zIndex: 50,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 52,
      paddingBottom: 12,
      borderBottomWidth: 1,
    },
    stickyBackBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    stickyTitle: {
      flex: 1,
      fontSize: 15,
      fontWeight: "700",
      letterSpacing: -0.3,
    },
    imageContainer: { height: IMAGE_HEIGHT, overflow: "hidden" },
    image: { width, height: IMAGE_HEIGHT },
    backButton: {
      position: "absolute",
      top: 52,
      left: 16,
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: "rgba(0,0,0,0.45)",
      justifyContent: "center",
      alignItems: "center",
    },
    imageCounter: {
      position: "absolute",
      top: 52,
      right: 16,
      backgroundColor: "rgba(0,0,0,0.5)",
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 20,
    },
    imageCounterText: { color: "#fff", fontSize: 12, fontWeight: "700" },
    ratingOverlay: {
      position: "absolute",
      bottom: 48,
      left: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      backgroundColor: "rgba(0,0,0,0.5)",
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 20,
    },
    ratingOverlayText: { color: "#F59E0B", fontSize: 13, fontWeight: "800" },
    ratingOverlaySub: { color: "rgba(255,255,255,0.7)", fontSize: 11 },
    imageDots: {
      position: "absolute",
      bottom: 18,
      left: 0,
      right: 0,
      flexDirection: "row",
      justifyContent: "center",
      gap: 5,
    },
    imageDot: {
      width: 5,
      height: 5,
      borderRadius: 2.5,
      backgroundColor: "rgba(255,255,255,0.4)",
    },
    imageDotActive: { width: 16, backgroundColor: "#fff" },
    content: {
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      marginTop: -28,
      paddingHorizontal: 20,
      paddingTop: 24,
    },
    titleBlock: { marginBottom: 20 },
    categoryPill: {
      alignSelf: "flex-start",
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 20,
      borderWidth: 1,
      marginBottom: 10,
    },
    categoryPillText: {
      fontSize: 11,
      fontWeight: "700",
      textTransform: "uppercase",
      letterSpacing: 0.6,
    },
    title: {
      fontSize: 24,
      fontWeight: "900",
      letterSpacing: -0.6,
      lineHeight: 30,
      marginBottom: 8,
    },
    titleMeta: { flexDirection: "row", alignItems: "center", gap: 4 },
    titleMetaText: { fontSize: 13, fontWeight: "500" },
    priceCard: {
      borderRadius: 20,
      padding: 20,
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 16,
    },
    priceLeft: { flex: 1 },
    priceLabel: {
      fontSize: 10,
      color: "rgba(255,255,255,0.65)",
      fontWeight: "600",
      textTransform: "uppercase",
      letterSpacing: 0.6,
      marginBottom: 4,
    },
    priceValue: {
      fontSize: 30,
      fontWeight: "900",
      color: "#fff",
      letterSpacing: -1,
    },
    priceDivider: {
      width: 1,
      height: 52,
      backgroundColor: "rgba(255,255,255,0.2)",
      marginHorizontal: 20,
    },
    priceRight: { alignItems: "flex-end", gap: 4 },
    priceReviews: {
      fontSize: 11,
      color: "rgba(255,255,255,0.65)",
      fontWeight: "500",
    },
    addReviewBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 3,
      backgroundColor: "rgba(255,255,255,0.15)",
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 16,
      marginTop: 4,
    },
    addReviewBtnText: { fontSize: 10, color: "#fff", fontWeight: "700" },
    infoGrid: {
      flexDirection: "row",
      borderRadius: 16,
      borderWidth: 1,
      padding: 16,
      marginBottom: 4,
    },
    infoGridDivider: { width: 1, marginHorizontal: 16 },
    description: { fontSize: 14, lineHeight: 24, fontWeight: "400" },
    notesCard: {
      flexDirection: "row",
      gap: 10,
      padding: 14,
      borderRadius: 14,
      borderWidth: 1,
    },
    notesText: { flex: 1, fontSize: 13, lineHeight: 21 },
    chipsWrap: { flexDirection: "row", flexWrap: "wrap" },
    mapWrapper: { borderRadius: 18, overflow: "hidden", borderWidth: 1 },
    hostCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      padding: 16,
      borderRadius: 18,
      borderWidth: 1,
    },
    hostAvatar: {
      width: 52,
      height: 52,
      borderRadius: 26,
      justifyContent: "center",
      alignItems: "center",
    },
    hostInfo: { flex: 1, gap: 3 },
    hostName: { fontSize: 15, fontWeight: "800", letterSpacing: -0.2 },
    verifiedBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      alignSelf: "flex-start",
      backgroundColor: "#DCFCE7",
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
    },
    verifiedText: { fontSize: 10, color: "#16A34A", fontWeight: "700" },
    hostPhone: { fontSize: 12, fontWeight: "500" },
    hostMsgBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      borderWidth: 1.5,
      justifyContent: "center",
      alignItems: "center",
    },
    footer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingHorizontal: 20,
      paddingVertical: 14,
      paddingBottom: 30,
      borderTopWidth: 1,
    },
    msgBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 6,
      paddingVertical: 13,
      paddingHorizontal: 16,
      borderRadius: 14,
      flex: 0.42,
    },
    msgBtnText: { fontSize: 13, fontWeight: "700" },
    msgBtnTextActive: { fontSize: 13, fontWeight: "700", color: "#fff" },
    bookBtnWrapper: {
      flex: 0.58,
      borderRadius: 14,
      shadowColor: "#8B5CF6",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.35,
      shadowRadius: 12,
      elevation: 6,
    },
    bookBtn: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 14,
      borderRadius: 14,
      gap: 8,
    },
    bookBtnText: {
      fontSize: 15,
      fontWeight: "800",
      color: "#fff",
      letterSpacing: -0.2,
    },
    bookBtnArrow: {
      width: 22,
      height: 22,
      borderRadius: 11,
      backgroundColor: "#fff",
      justifyContent: "center",
      alignItems: "center",
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.55)",
      justifyContent: "flex-end",
    },
    modalSheet: {
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 20,
      paddingBottom: 40,
    },
    sheetHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: "rgba(0,0,0,0.15)",
      alignSelf: "center",
      marginBottom: 20,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 18,
    },
    modalTitle: { fontSize: 19, fontWeight: "800", letterSpacing: -0.4 },
    modalSub: { fontSize: 12, fontWeight: "500", marginTop: 2 },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    miniCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      padding: 10,
      borderRadius: 14,
      borderWidth: 1,
      marginBottom: 16,
    },
    miniImg: { width: 48, height: 48, borderRadius: 10 },
    miniTitle: { fontSize: 13, fontWeight: "700" },
    miniSub: { fontSize: 11, marginTop: 2 },
    msgInput: {
      borderRadius: 14,
      borderWidth: 1,
      padding: 14,
      fontSize: 14,
      minHeight: 110,
      textAlignVertical: "top",
    },
    charCount: {
      fontSize: 11,
      textAlign: "right",
      marginTop: 6,
      marginBottom: 4,
    },
    msgHint: {
      fontSize: 11,
      color: "#6B7280",
      marginBottom: 16,
      lineHeight: 16,
    },
    sendBtn: { borderRadius: 14, overflow: "hidden" },
    sendBtnGrad: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      paddingVertical: 15,
    },
    sendBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
    starPicker: {
      flexDirection: "row",
      justifyContent: "center",
      gap: 8,
      marginBottom: 8,
    },
    starLabel: {
      textAlign: "center",
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 18,
    },
  });
}
